apiVersion: v1
type: cli/v1
name: nexus-push
version: 0.0.1
runtime: subprocess
config:
  usage: Push a chart directory or package to a Nexus Helm repository
  shortHelp: Upload Helm charts to Nexus over HTTP(S)
  ignoreFlags: false
runtimeConfig:
  platformCommand:
    - command: ${HELM_PLUGIN_DIR}/push.sh
